project:
  title: "No Fairness without Awareness"
  type: book
  output-dir: _book

book:
  title: "No Fairness without Awareness"
  author: "Theo Bakker"
  date: last-modified
  navbar: 
    right:
      - icon: info-square
        href: https://www.dehaagsehogeschool.nl/onderzoek/lectoraten/learning-technology-analytics
        aria-label: Over het lectoraat Learning Technology & Analytics
  repo-url: https://github.com/LTA-HHs/lta-hhs-tidymodels-studiesucces/
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd
    
    - part: "Analyse"
      chapters:
        - H1_Index_basis.qmd
        - H2_Index_verdieping_factoren.qmd
        - H3_Index_verdieping_kansengelijkheid.qmd

editor: visual

# execute:
#  keep-md: true

website:
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com
  
## Citaties
link-citations: true
bibliography: bibliography/references.bib
csl: bibliography/apa.csl

# Taalinstellingen
lang: nl
language: 
  other-links-title: "Meer informatie"
  
# Lightbox
lightbox: true

## Output instellingen
format:
  html:
    number-sections: true
    smooth-scroll: true
    link-external-icon: true
    html-math-method: katex
    
    ## Code instellingen
    code-fold: true
    code-summary: "Toon code"
    
    ## Theme instellingen
    theme: 
    - lumen
    - "01. Includes/scss/lta.scss"
    
    ## Output instellingen
    self-contained: true
    standalone: true
    embed-resources: true
    
    ## Links rechterzijde
    toc: true
    toc-title: Inhoudsopgave
    toc-depth: 3
    other-links:
      - text: "Over het lectoraat Learning Technology & Analytics"
        href: https://www.dehaagsehogeschool.nl/onderzoek/lectoraten/learning-technology-analytics
      - text: "Over het onderzoeksprogramma 'No Fairness without Awareness'"
        href: https://www.dehaagsehogeschool.nl/onderzoek/kenniscentra/no-fairness-without-awareness
