# Project settings
project:
  type: book
  
# Book settings
book:
  author: "Dr. Theo Bakker, lector Learning Technology & Analytics, De Haagse Hogeschool"
  date: last-modified
  bread-crumbs: false
  navbar: 
    right:
      - icon: info-square
        href: https://www.dehaagsehogeschool.nl/onderzoek/centres-expertise/no-fairness-without-awareness
        aria-label: Over het onderzoek No Fairness without Awareness
  repo-url: https://github.com/LTA-HHs/lta-hhs-tidymodels-studiesucces/
  repo-branch: main
  repo-actions: [issue]

profile:
  group: 
    - [basic, advanced]

# Brand settings
brand: brand/_brand.yml  

# Editor
editor: source

# Execute settings (default)
execute:
  keep-md: false
  echo: false

# Citations
link-citations: true
bibliography: bibliography/references.bib
csl: bibliography/apa.csl

# Language settings
lang: nl
language: 
  other-links-title: "Meer informatie"
  
# Lightbox
lightbox: true

# Output settings
format:
  html:
    number-sections: true
    smooth-scroll: true
    link-external-icon: true
    html-math-method: katex
    
    # Fontsize
    fontsize: 1.1em
    
    # Comments
    comments:
      hypothesis: true
    
    # Theme settings
    theme: 
    - lumen
    - brand
    - "brand/scss/default.scss"
    
    # Output settings
    self-contained: true
    standalone: true
    embed-resources: true
    
    # Hyperlinks on the right
    toc: true
    toc-title: Inhoudsopgave
    toc-depth: 3
    other-links:
      - text: "Over het lectoraat Learning Technology & Analytics"
        href: https://www.dehaagsehogeschool.nl/onderzoek/lectoraten/learning-technology-analytics
      - text: "Over het onderzoeksprogramma 'No Fairness without Awareness'"
        href: https://www.dehaagsehogeschool.nl/onderzoek/kenniscentra/no-fairness-without-awareness
        
# Other settings
config:
  environment: "development" # options: development, production
