project:
  title: "Tidymodels"

editor: visual

# execute:
#  keep-md: true
  
# Taalinstellingen
lang: nl
language: 
  other-links-title: "Meer informatie"

## Output instellingen
format:
  html:
    number-sections: true
    smooth-scroll: true
    link-external-icon: true
    html-math-method: katex
    
    ## Code instellingen
    code-fold: true
    code-summary: "Toon code"
    
    ## Theme instellingen
    theme: 
    - lumen
    - "01. Includes/scss/lta.scss"
    
    ## Output instellingen
    self-contained: true
    standalone: true
    embed-resources: true
    
    ## Links rechterzijde
    toc: true
    toc-title: Inhoudsopgave
    other-links:
      - text: "Over het lectoraat Learning Technology & Analytics"
        href: https://www.dehaagsehogeschool.nl/onderzoek/lectoraten/learning-technology-analytics
      - text: "Over het onderzoeksprogramma 'No Fairness without Awareness'"
        href: https://www.dehaagsehogeschool.nl/onderzoek/kenniscentra/no-fairness-without-awareness
