name: Render Quarto Documents in docs/

on:
  push:
    paths:
      - "docs/*.qmd"
  workflow_dispatch:

jobs:
  render-quarto:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Install Quarto (latest stable)
        uses: quarto-dev/quarto-actions/setup@v2

      - name: 📝 Render all .qmd files in docs/ to .md
        run: |
          for file in docs/*.qmd; do
            quarto render "$file" --to gfm
          done

      - name: 🔄 Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.md
          # Check for ANY changes, not just staged changes
          if [[ $(git diff --quiet) ]]; then  # Check if there are ANY changes
            git commit -m "Automatically rendered Quarto documents in docs/"
            git push origin ${{ github.ref }} # Explicitly push to the same branch
          fi
