name: Render Quarto Documents in docs/

on:
  push:
    paths:
      - "docs/*.qmd"
  workflow_dispatch:

jobs:
  render-quarto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Install Quarto (latest stable)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          cache: true

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION', 'renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R packages and renv
        run: |
          if [ -f "renv.lock" ]; then
            R -e "install.packages('renv')" # Install renv FIRST
            Rscript -e 'renv::restore()'
          else
            R -e "install.packages(c('badger','rmarkdown','knitr'))"
          fi

      - name: Check installed packages
        run: Rscript -e "installed.packages()"

      - name: Render all .qmd files in docs/ to .md
        run: |
          for file in docs/*.qmd; do
            quarto render "$file" --to gfm
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.md
          if [[ $(git diff --quiet) ]]; then
            git commit -m "Automatically rendered Quarto documents in docs/"
            git push origin ${{ github.ref }}
          fi
